name: Pipeline-CI-CD
on:
  push: 
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: obtendo o código
      uses: actions/checkout@v4.2.2
    - name: autenticando no docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build da imagem
      uses: docker/build-push-action@v6
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          rangelcr/first-image-pipe:v${{ github.run_number }}
          rangelcr/first-image-pipe:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: obtendo o código
      uses: actions/checkout@v4.2.2    
    - name: Configurando contexto do k8s
      uses: Azure/k8s-set-context@v4.0.0
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG }}
    - name: Aplicando manifesto
    - uses: Azure/k8s-deploy@v5
      with:
       manifests: |
          ./k8s/deployment.yaml
       images: | 
          rangelcr/first-image-pipe:v${{ github.run_number }}
    
    
